# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PullDown-Picture-ToBig' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PullDown-Picture-ToBig
pod 'Masonry', '~> 1.1.0'
  target 'PullDown-Picture-ToBigTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PullDown-Picture-ToBigUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
