# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MenuTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MenuTest
pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.0'
  target 'MenuTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MenuTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
