# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDSC_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for DDSC_Swift
pod 'Alamofire', '~> 4.7.2'
pod 'SnapKit', '~> 4.0.0'
pod 'Kingfisher', '~> 4.7.0'
pod 'SwiftyJSON', '~> 4.1.0'
  target 'DDSC_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDSC_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
